#################################### server port config start ##########################################################
server:
  port: 9095
#################################### server port config end ############################################################

#################################### spring config start   #############################################################
spring:
  profiles:
    active: prod
  tomcat:
    max-http-post-size: -1
  application:
    name: wx-chat-bot
#################################### spring config end   ###############################################################